name: CI dev

on: 
  push:
    branches:
      - dev

env:
  JAVA_VERSION: '11'
  JAVA_DISTRIBUTION: temurin                       # set this to the Java version to use
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: mesdepenses-api-test
  #################################################

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - uses: actions/upload-artifact@v3
        with:
          name: mesdepenses-api-app
          path: '${{ github.workspace }}/target/*.jar' 

