name: Test deployment

on: 
  push:
    branches:
      - test

env:
  JAVA_VERSION: '11'
  JAVA_DISTRIBUTION: temurin                       # set this to the Java version to use
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: mesdepenses-api-test
  #################################################

jobs:
  Deploy-to-Azure:
    runs-on: ubuntu-latest
    name: Deploy app container to Azure
    steps:
      # - name: Download built artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: mesdepenses-api-test-app
      #     path: artifact

      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.23.0
        with:
          name: mesdepenses-api-app
          workflow: ci-dev.yml
          workflow_conclusion: success
          branch: dev
          
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          package: '*.jar'

      - name: Azure logout
        run: |
          az logout

      - uses: actions/upload-artifact@v3
        with:
          name: mesdepenses-api-app
