name: Stage the app

on: 
  pull_request:
    types: [labeled]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: mesdepenses-api-dev
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  JAVA_VERSION: '11'
  JAVA_DISTRIBUTION: temurin                       # set this to the Java version to use
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: mesdepenses-api-dev
  #################################################

jobs:
  Build:
    if: contains(github.event.pull_request.labels.*.name, 'stage')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java version
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install
    
      - uses: actions/upload-artifact@main
        with:
          name: mesdepenses-api-dev-app
          path: '${{ github.workspace }}/target/*.jar'

  Deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Build image and store in GitHub Packages
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download built artifact
        uses: actions/download-artifact@main
        with:
          name: mesdepenses-api-dev-app

  Deploy-to-Azure:
    runs-on: ubuntu-latest
    needs: Build-Docker-Image
    name: Deploy app container to Azure
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          package: '*.jar'

      - name: Azure logout
        run: |
          az logout
