name: 21 - Production deployment

on: 
  push:
    branches:
      - prod

env:
  JAVA_VERSION: '11'
  JAVA_DISTRIBUTION: temurin                       # set this to the Java version to use
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: mesdepenses-api-prod
  #################################################

jobs:
  Deploy-to-Azure:
    runs-on: ubuntu-latest
    needs: Build
    name: Deploy app container to Azure
    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.23.0
        with:
          name: mesdepenses-api-prod-app
          workflow: deploy-test.yml
          workflow_conclusion: success
          branch: test

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          package: '*.jar'

      - name: Azure logout
        run: |
          az logout
